### ISSUE TITLE
App cannot add tasks

### ISSUE THREAD

**Issue by jrm86** [smacademic/project-cgkm#14]
The app does not allow one to add new tasks

This requirement is listed in the SRS [here](https://github.com/smacademic/project-cgkm/wiki/Software-Requirements-Specification).

**Comment by KevinKelly25** [comment]
To expand on this issue. I believe the add task can also be implemented in the following way, taken from the function descriptions wiki.

## Add Task Function
**Signature**: `Task addTask ( String title, {String description = null, DateTime dueDate = null, String location = null })`

**Parameter 1**: `title` represents the title of the Task

**Parameter 2**: `description` is the information that describes the task objective. This is null by default

**Parameter 3**: `dueDate` is the date when the task should be completed by. This is null by default

**Parameter 4**: `location` is where the task takes place. This is null by default

**Return**: Returns the created task

**Description**: The parameters supply needed information to create a Task within the SQLite database with the exception of the ID. This ID needs to be generated with a UUID. This data is sent to the SQLite database to be inserted into the task table. If successfully inserted the data should be used to create a task object. That task object should then be added to the list of tasks belonging to the Arc which called the instance method.

Also, I do believe this issue should address the ability to remove tasks due to the very related functionality. This could be done in the following way:

## Remove Task Function
**Signature**: Void removeTask ( String taskID )

**Parameter 1**: taskID is the ID of the task to be deleted

**Description**: Given a taskID it deletes the task entry for the supplied task ID. It then searches the collection of task objects in the instance of Arc until it finds the correct task. It then removes and deletes that task from the arc object. The deletion of the class will call the destructor function of the Task object.

**Comment by jgrabowski121** [comment]
This issue was closed by #92
