### ISSUE TITLE
Need Settings Screen

### ISSUE THREAD

**Issue by MatthewChastain** [smacademic/project-cgkm#31]
ArcPlanner needs a Settings screen to facilitate changing notification, login, and other settings. Most of these settings will involve extensions but setting up this screen early on in development will allow for easily adding extensions later on. 

A visual template of the UI along with details for the screen can be found [here](https://github.com/smacademic/project-cgkm/wiki/ArcPlanner-UI-Design-Template#settings).

**Comment by jgrabowski121** [comment]
I have published the branch [ add-settings-screen](https://github.com/smacademic/project-cgkm/tree/add-settings-screen), it is not ready for a PR yet but feel free to view it as it is almost complete.

Note: I used a `FlatButton` as opposed to a `RaisedButton` for the selectable settings boxes in the scrollable list, please reply with feedback on this implementation.

**Comment by KevinKelly25** [comment]
I see the three settings buttons and they send me to the about screen which I believe is an expected behavior. There also is two blue circle buttons at the bottom and there should probably only be one. Again, I think this was added on purpose for testing. 

Other then the expected issues I mentioned I think this is a good start. Are we going to have a separate screen for each setting, will it be a drop down or some other method? If it will be a drop down it may be worth adding example drop down lists for now.

**Comment by jgrabowski121** [comment]
@KevinKelly25 thank you for viewing the progress and for the feedback. I am going to remove the two buttons from the bottom of the screen and they will be replaced by a single "back" button as planned. Additionally, there is no plan for drop down lists currently so I do not believe they will be added for M4.
